Add Qovery as deployment option
blitz-js/blitzjs.com pull request #414
Opened 2021-03-18 09:30 UTC by arnaudjnn

Hi Blitz team,

As discussed this week with @evoxmusic I added docs on deploying Blitz to Qovery - feedback is welcome.

Arnaud.

2021-03-18 14:20 UTC, JuanM04 commented
Thank you for your contribution!!

While we review your guide, could you sync your branch with `main`? I just pushed some changes: `documentation.js` was deleted in favor of `documentation.json`

2021-03-19 14:50 UTC, flybayer requested changes

2021-03-19 14:50 UTC, flybayer commented on app/core/navs/documentation.js
> +      },
Thanks @arnaudjnn!

Please move this to between Heroku and Vercel.

2021-03-19 14:50 UTC, flybayer commented on app/pages/docs/deploy-qovery.mdx
> +5. Give a mount point.
Can you add more docs to this section? I.e. what is storage? Is it needed? What is it used for?

2021-03-19 14:50 UTC, flybayer commented on app/pages/docs/deploy-qovery.mdx
> +7. Click "Deploy"
- You need to add a step for adding the `SESSION_SECRET_KEY` environment variable
- You need to add a step for changing package.json build script to `NODE_ENV=production blitz build && blitz prisma migrate deploy --preview-feature`

Those are both in instructions for the other platforms.

2021-04-24 18:47 UTC, flybayer requested changes
Sweet @arnaudjnn, still one change left

2021-04-24 18:47 UTC, flybayer commented on app/core/navs/documentation.js
> +      },
Still need to change this

2021-04-24 18:47 UTC, flybayer commented on app/pages/docs/deploy-qovery.mdx
> +release: npx blitz prisma migrate deploy --preview-feature
```suggestion
release: npx blitz prisma migrate deploy
```

2021-11-17 17:11 UTC, JuanM04 commented
Merged. I couldn't update their branch because it was deleted

2021-11-17 17:11 UTC, closed without merging