Remove mentions of `as` (no longer required)
blitz-js/blitzjs.com pull request #429
Opened 2021-04-06 06:25 UTC by Skn0tt

2021-04-06 06:37 UTC, Skn0tt commented
> `as` - Optional decorator for the path that will be shown in the browser URL bar. Before Next.js 9.5.3 this was used for dynamic routes, check our previous docs to see how it worked
> ~ https://nextjs.org/docs/api-reference/next/link

2021-04-06 15:34 UTC, JuanM04 requested changes
Awesome!

2021-04-06 15:34 UTC, JuanM04 commented on app/pages/docs/link.mdx
> -
Maybe you could leave "Here's an example of how to create a list of links" or something similar

2021-04-08 16:07 UTC, JuanM04 approved these changes

2021-04-08 16:07 UTC, merged