add a troubleshooting part with debug logging
blitz-js/blitzjs.com pull request #560
Opened 2021-10-03 16:01 UTC by g3offrey

During my investigation on https://github.com/blitz-js/blitz/pull/2792, I discovered the `DEBUG` environment variable.
I think this variable could have helped the reporter of https://github.com/blitz-js/blitz/issues/2751 to troubleshoot his issue on Blitz console.

I initiated a new section `troubleshooting` that can contains a lot of tips like that.
That could be a "must read" for future users that encounter an issue and need help debugging their Blitz projects.

Hope you'll like this 😄

2021-10-04 15:11 UTC, flybayer commented
Awesome, thanks @g3offrey! Can you also add a section showing how to enabled debug in the browser? (`localStorage.debug = 'blitz:*'`)

Location in the menu looks good.

2021-10-04 19:01 UTC, g3offrey commented
Indeed, that is a must known. 
I wasn't aware of this part, I tried on my end and added the documentation about that in my latest commit, if you want to check it out. 😄

2021-10-04 20:21 UTC, JuanM04 requested changes
Awesome, thanks! Here are some suggestions:

2021-10-04 20:21 UTC, JuanM04 commented on app/pages/docs/troubleshooting.mdx
> +- blitz:utils
Wrap these namespaces in `` (back tick) so they appear like this: `blitz:utils`

2021-10-04 20:21 UTC, JuanM04 commented on app/pages/docs/troubleshooting.mdx
> +enabled.
```suggestion
Please, be sure that the devtools console has the verbose level
enabled.
```

2021-10-05 13:38 UTC, g3offrey commented on app/pages/docs/troubleshooting.mdx
> +- blitz:utils
Sure 😄

2021-10-05 13:40 UTC, g3offrey commented
Thank you for your feedback @JuanM04, I updated the PR. 😄

2021-10-05 14:50 UTC, flybayer commented on app/pages/docs/troubleshooting.mdx
> +localStorage.setItem('debug', 'blitz:*')
simpler :)
```suggestion
localStorage.debug = 'blitz:*'
```

2021-10-05 14:50 UTC, flybayer approved these changes

2021-10-05 14:51 UTC, merged