fix HTML titles are now displayed in HTML tag format.
blitz-js/blitzjs.com pull request #645
Opened 2021-12-31 11:13 UTC by mochi-sann

fix #644 
## before 
![image](https://user-images.githubusercontent.com/44772513/147820285-d0405a95-e6ff-4368-b2af-7b7c46c5310d.png)
## afte
![Future_of_Blitz_-_Vivaldi](https://user-images.githubusercontent.com/44772513/147820306-e44a5ceb-eacf-420e-abf0-a40d9481da54.png)
r

2021-12-31 11:49 UTC, beerose reviewed
Thanks!

2021-12-31 11:49 UTC, beerose commented on app/core/components/Search.js
> +  }
Let's keep the function name lowercase
```suggestion

  const convertToHtmlTag = (value) => {
    return value.replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">")
  }
```

2021-12-31 12:02 UTC, mochi-sann commented
Thank you for your review!

2021-12-31 13:34 UTC, JuanM04 requested changes
Nice!
I noticed that `hierarchy.lvl0` doesn't need to be converted anymore, so the code can be reduced to this:

```js
// The titles are encoded, so we need to decode them.
// &lt;Script&gt; --> <Script>
const _highlightResult = {...item._highlightResult}

_highlightResult.hierarchy.lvl0.value = _highlightResult.hierarchy.lvl0.value
  .replace(/&amp;/g, "&")
  .replace(/&lt;/g, "<")
  .replace(/&gt;/g, ">")

return {
  ...item,
  _highlightResult,
  url: `${a.pathname}${hash}`,
}
```

2022-01-01 00:43 UTC, mochi-sann commented
Thank you ,review
I've reduced the code as you pointed out.

2022-01-01 00:58 UTC, merged