Improve the @blitzjs/next documentation
blitz-js/blitzjs.com pull request #750
Opened 2022-08-23 18:39 UTC by dillonraphael

- Add __Example__ headings to client & server sections of @blitzjs/next
- Add __API__ headings with __Arguments__ & __Returns__ for both the client & server sections of @blitzjs/next

2022-08-24 08:54 UTC, beerose requested changes

2022-08-24 08:54 UTC, beerose commented on app/pages/docs/blitzjs-next.mdx
>  Inside `app > blitz-client.ts`
```suggestion
### Example {#blitzjs-next-client-example}

Inside `app/blitz-client.ts`:
```

2022-08-24 08:54 UTC, beerose commented on app/pages/docs/blitzjs-next.mdx
>  Inside `app > blitz-client.ts`
I would remove the `Example` heading and tell users that they must create a `blitz-client.ts` file in <root>/app directory (or somewhere else). Same for the server configuration. In other words — I would write these docs with more explanations on why and what users are supposed to do.

2022-09-06 14:28 UTC, flybayer approved these changes

2022-09-16 12:45 UTC, beerose approved these changes

2022-09-16 14:29 UTC, merged