Update blitz-next docs
blitz-js/blitzjs.com pull request #780
Opened 2022-10-12 02:00 UTC by dillonraphael

2022-10-17 07:03 UTC, beerose commented on app/pages/docs/blitzjs-next.mdx
> +The Blitz CLI supports running custom Next.js servers. This means you can compile typescript and use the blitz cli to inject env variables. By default, the CLI checks for `server/index.ts` or `server
Why not javascript? You only mention TypeScript. Also, you should link to Next.js docs

2022-10-17 07:03 UTC, beerose commented on app/pages/docs/blitzjs-next.mdx
> +...
What are these dots?

2022-10-17 07:04 UTC, beerose commented on app/pages/docs/blitzjs-next.mdx
> +You can set the types returned from the Next.js data fetching functions. All Blitzjs wrappers for the Nextjs functions accept a generic. Same with the `BlitzPage` type.
```suggestion
You can set the types returned from the Next.js data fetching functions. All Blitz.js wrappers for the Next.js functions accept a generic. Same with the `BlitzPage` type.
```

2022-10-17 07:05 UTC, beerose commented on app/pages/docs/blitzjs-next.mdx
> +...
??

2022-10-18 02:23 UTC, dillonraphael commented on app/pages/docs/blitzjs-next.mdx
> +...
The dots are abbreviation. Should I remove?

2022-10-19 07:27 UTC, beerose requested changes
Please run the linter on the changed file!

2022-10-22 09:19 UTC, beerose approved these changes

2022-10-25 01:52 UTC, merged