Add blitz auth + next guide
blitz-js/blitzjs.com pull request #793
Opened 2022-11-09 10:18 UTC by beerose

2022-11-09 19:25 UTC, dillonraphael requested changes

2022-11-09 19:25 UTC, dillonraphael commented on app/pages/docs/blitz-auth-with-next.mdx
> +### Add `pages/api/signup.ts` file {#add-signup-route}
We're placing the `pages` directory inside `src` now

2022-11-09 19:25 UTC, dillonraphael commented on app/pages/docs/blitz-auth-with-next.mdx
> +import { api } from "../../src/blitz-server"
See above

2022-11-09 19:25 UTC, dillonraphael commented on app/pages/docs/blitz-auth-with-next.mdx
> +### Add `pages/api/login.ts` {#add-login-route}
Same here

2022-11-09 19:25 UTC, dillonraphael commented on app/pages/docs/blitz-auth-with-next.mdx
> +import { api } from "../../src/blitz-server"
And here

2022-11-15 17:32 UTC, flybayer commented on app/pages/docs/blitz-auth-with-next.mdx
> +##### Modify Prisma schema {#modify-prisma-schema}
```suggestion
##### Modify Prisma schema
```

2022-11-15 17:33 UTC, flybayer approved these changes

2022-11-15 17:33 UTC, merged