Update usage-next-13.mdx: `BlitzProvider` as client component
blitz-js/blitzjs.com pull request #847
Opened 2023-10-13 04:51 UTC by tordans

The also the request for help at https://discord.com/channels/802917734999523368/1161576668863922176

## Change

My understanding is, that `BlitzProvider` is a client component and the way I understand the app directory means that everything below in the include-tree needs to be a client component as well.

## Testcase

1. checkout https://github.com/FixMyBerlin/blitz-test/commits/blitzprovider-test which is the error case without the use client in the layout file that holds the blitzprovider
2. See error

**Error**
> Unhandled Runtime Error
Error: Unsupported Server Component type: undefined

<img width="976" alt="image" src="https://github.com/blitz-js/blitzjs.com/assets/111561/47b33657-67b5-4cc7-9838-a171cda9f71d">

2023-10-13 09:26 UTC, siddhsuresh commented
@tordans I do not understand this, `BlitzProvider` is a client component and takes the rest of the application as props. We are following this pattern https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#supported-pattern-passing-server-components-to-client-components-as-props

We can definitely use server components with blitz.

2023-10-13 09:29 UTC, siddhsuresh requested changes

2023-10-13 09:29 UTC, siddhsuresh commented on app/pages/docs/usage-next-13.mdx
> +'use client'
not required

2023-10-13 09:29 UTC, siddhsuresh commented on app/pages/docs/usage-next-13.mdx
> +Add the new `use client` directive to **all** files in the include-tree below [`BlitzProvider`](https://blitzjs.com/docs/usage-next-13#blitz-provider), which is a client component.
`all` files?

2023-10-13 11:09 UTC, tordans commented on app/pages/docs/usage-next-13.mdx
> +Add the new `use client` directive to **all** files in the include-tree below [`BlitzProvider`](https://blitzjs.com/docs/usage-next-13#blitz-provider), which is a client component.
The thing is, that https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#unsupported-pattern-importing-server-components-into-client-components

> You cannot import a Server Component into a Client Component

Results is a bad error message 

> Error: Unsupported Server Component type: undefined

One thing I did was to remove all barrel files from our project in order to work around this issue, as suggested in https://github.com/vercel/next.js/issues/41940

(But in the end we added `'use client'` to all files (for now), just to get to a working version.)

My current understanding is: Since I cannot import server components into client components and I cannot audit every include, for [the slot-workaround](https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#supported-pattern-passing-server-components-to-client-components-as-props) you mentioned, I have to add `use client` to all files that are imported in other files.

2023-10-13 11:13 UTC, tordans commented on app/pages/docs/usage-next-13.mdx
> +'use client'
I am happy to learn how :-). The "Testcase" I described above shows the issue. Add/remove the "use client" and it works or doen't…

2023-10-25 14:50 UTC, tordans commented
The changes I propose here are wrong, I will close the PR.

2023-10-25 14:50 UTC, closed without merging