docs
blitz-js/blitzjs.com pull request #860
Opened 2024-06-16 16:50 UTC by siddhsuresh

2024-06-17 19:52 UTC, flybayer commented on app/pages/docs/rpc-setup.mdx
> +4.1 App router (recommended):
formatting here doesn't look good. Let's add clear headings like on the auth page

2024-06-17 19:53 UTC, flybayer commented on app/pages/docs/rpc-setup.mdx
> +`[[...blitz]]/route.ts` file, and add the following lines:
```suggestion
Create an `app/api/rpc/[[...blitz]]` directory in your `src` directory with
a `route.ts` file, and add the following lines:
```
```suggestion
Create an `app/api/rpc` directory in your `src` directory with
`[[...blitz]]/route.ts` file, and add the following lines:
```
```suggestion
Create an `app/api/rpc` directory in your `src` directory with
`[[...blitz]]/route.ts` file, and add the following lines:
```

2024-06-17 19:54 UTC, flybayer reviewed
see comments

2024-06-17 19:57 UTC, flybayer requested changes
somewhere you need to fully document the api, arguments, and return  of both `withBlitzAuth` and `rpcAppHandler`

2024-06-18 11:17 UTC, siddhsuresh commented on app/pages/docs/rpc-setup.mdx
> +4.1 App router (recommended):
updated

2024-07-18 22:29 UTC, flybayer reviewed
otherwise the content looks good

2024-07-18 22:29 UTC, flybayer commented on app/pages/docs/rpc-config.mdx
> +  logged with the `debug` level.
list formatting is broken

2024-07-18 22:29 UTC, flybayer commented on app/pages/docs/auth-server.mdx
> +- `handlers: { [method: string]: Handler })` - An object of handlers where
all the list formats seem broken

2024-07-18 22:29 UTC, flybayer commented on app/pages/docs/auth-server.mdx
> +##### Signature
this seems out of place?
```suggestion
```

2024-08-14 14:15 UTC, merged